exports.downloader = require('./downloader')
exports.urlShortener = require('./shortener')
exports.getLocationData = require('./location')
exports.rugaapi = require('./rugaApi')
exports.welkom = require('./welcome')
exports.meme = require('./meme')
//exports.chatgpt = require('./chatgpt')
exports.imagine = require('./deepai.js')
